name: publish
on:
  release:
    types: [published]
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: install packages
        run: dotnet restore
          
      - name: build
        run: dotnet build

      - name: test
        run: dotnet test
        
      - name: Create package(s)
        run: dotnet pack --configuration Release --no-build

      - name: Publish packages
        run: dotnet nuget push **/*.nupkg -k ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json